services:
  nodered:
    image: nodered/node-red
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    restart: on-failure
volumes:
  node-red-data:
networks:
  node-red-net:
#