{
 "title": "da",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "host",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "host",
     "query": "SELECT \"IP VPN\", \"WLAN LTE Status\", \"Free RAM\", \"Free Disk\" FROM \"host\" WHERE $timeFilter ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "Free Disk" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU, %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": 10,
     "measurement": "host",
     "query": "SELECT \"CPU Usage, %\" FROM \"host\"",
     "select": [
      [
       { "params": [ "CPU Usage, %" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU, °C",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "host",
     "select": [
      [
       { "params": [ "CPU Temperatur, °C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "opc",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opc",
     "query": "SELECT Tankniveau FROM \"opc\"",
     "select": [
      [
       { "params": [ "Tanktemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opc",
     "query": "SELECT Tanktemp FROM \"opc\"",
     "select": [
      [
       { "params": [ "Tanktemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opc",
     "query": "SELECT Volumenstrom FROM \"opc\"",
     "select": [
      [
       { "params": [ "Tanktemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}