version: '3'
services:
  influxdb:
    image: anberra/influxdb-armv7
    container_name: influxdb1
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - '8086:8086'

  grafana:
    image: anberra/grafana-armv7
    container_name: grafana1
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    links:
      - influxdb
    depends_on:
      - influxdb

volumes:
  influxdb:
  grafana:
