# Generated by Django 4.2.3 on 2023-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=50)),
                ('Beschreibung', models.CharField(max_length=200)),
                ('Berechtigen', models.BooleanField(default=False)),
                ('Klasse', models.CharField(max_length=50)),
                ('Typ', models.CharField(max_length=50)),
                ('Abtastfrequenz', models.CharField(max_length=50)),
                ('Anweisung', models.CharField(max_length=200)),
                ('LWert', models.CharField(max_length=200)),
            ],
        ),
    ]
