# Generated by Django 4.2.6 on 2023-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Berechtigen', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Periode', models.PositiveIntegerField(default=1)),
                ('Start', models.PositiveIntegerField(default=1)),
                ('skript', models.BinaryField(max_length=65000)),
            ],
        ),
        migrations.CreateModel(
            name='db2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einstellungen', models.BinaryField(max_length=65000)),
            ],
        ),
    ]