# Generated by Django 5.0.1 on 2024-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db1',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='db1',
            name='skript',
            field=models.TextField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='db2',
            name='Einstellungen',
            field=models.TextField(max_length=65000),
        ),
    ]
