version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/kbwiot/tasks_db.sqlite3
        target: /tasks_db.sqlite3
    ports:
      - 8000:8000
    image: andreyvus/django2
    container_name: django2
#    command: python manage.py runserver 0:8000
#pip freeze > requirements.txt
#docker-compose build
#docker push andreyvus/django2
#docker-compose up -d
#docker logs django2
#docker exec -it django2 bash
#docker stop django2
#docker rm django2
#docker rmi django2
#docker system prune